/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UserGoalsContainer {
    'name': string;
  }
  interface UserGoalsContainerAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface UserGoalsForm {}
  interface UserGoalsFormAttributes extends StencilHTMLAttributes {
    'onGoalUpdated'?: (event: CustomEvent) => void;
  }

  interface UserGoalsGauge {
    'data': number;
    'goal': number;
  }
  interface UserGoalsGaugeAttributes extends StencilHTMLAttributes {
    'data'?: number;
    'goal'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UserGoalsContainer': Components.UserGoalsContainer;
    'UserGoalsForm': Components.UserGoalsForm;
    'UserGoalsGauge': Components.UserGoalsGauge;
  }

  interface StencilIntrinsicElements {
    'user-goals-container': Components.UserGoalsContainerAttributes;
    'user-goals-form': Components.UserGoalsFormAttributes;
    'user-goals-gauge': Components.UserGoalsGaugeAttributes;
  }


  interface HTMLUserGoalsContainerElement extends Components.UserGoalsContainer, HTMLStencilElement {}
  var HTMLUserGoalsContainerElement: {
    prototype: HTMLUserGoalsContainerElement;
    new (): HTMLUserGoalsContainerElement;
  };

  interface HTMLUserGoalsFormElement extends Components.UserGoalsForm, HTMLStencilElement {}
  var HTMLUserGoalsFormElement: {
    prototype: HTMLUserGoalsFormElement;
    new (): HTMLUserGoalsFormElement;
  };

  interface HTMLUserGoalsGaugeElement extends Components.UserGoalsGauge, HTMLStencilElement {}
  var HTMLUserGoalsGaugeElement: {
    prototype: HTMLUserGoalsGaugeElement;
    new (): HTMLUserGoalsGaugeElement;
  };

  interface HTMLElementTagNameMap {
    'user-goals-container': HTMLUserGoalsContainerElement
    'user-goals-form': HTMLUserGoalsFormElement
    'user-goals-gauge': HTMLUserGoalsGaugeElement
  }

  interface ElementTagNameMap {
    'user-goals-container': HTMLUserGoalsContainerElement;
    'user-goals-form': HTMLUserGoalsFormElement;
    'user-goals-gauge': HTMLUserGoalsGaugeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
